name:                arboretum
version:             0.1.0.0
github:              "ebronasco/arboretum"
license:             BSD-3-Clause
author:              "Eugen Bronasco"
maintainer:          "ebronasco@gmail.com"
copyright:           "2023"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ebronasco/arboretum#readme>

dependencies:
- base >= 4.7 && < 5
- groups
- multiset
- directory
- typed-process
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields

library:
  source-dirs: src

executables:
  arboretum-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
#    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arboretum
    when:
    - condition: false
      other-modules: Paths_arboretum

tests:
  arboretum-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arboretum
    - doctest
    - QuickCheck
    - mtl
