{-# LANGUAGE PatternSynonyms #-}

module SymLists (
--     Sum (Zero),
--     pattern (:+),
--     (+:),
--     PowerSeries (..),
) where

import Data.Group
import GradedList

--------------- Sum ----------------
-- 
-- data Term k a = k :*^ a deriving (Eq)
-- 
-- getBasis :: Term k a -> a
-- getBasis (_ :*^ a) = a
-- 
-- getScalar :: Term k a -> k
-- getScalar (k :*^ _) = k
-- 
-- pattern (:+) :: Term k a -> Sum k a -> Sum k a
-- pattern t :+ s <- Sum t s
-- 
-- data Sum k a = Sum (Term k a) (Sum k a) | Zero
-- 
-- fromListS :: (Num k, Eq k, Eq a) => [Term k a] -> Sum k a
-- fromListS [] = Zero
-- fromListS (h : t) = h +: fromListS t
-- 
-- toListS :: Sum k a -> [Term k a]
-- toListS Zero = []
-- toListS (h :+ s) = h : toListS s
-- 
-- instance (Show k, Show a) => Show (Sum k a) where
--     show (t :+ Zero) = show t
--     show (t :+ s) = show t ++ " + " ++ show s
--     show Zero = "0"
-- 
-- infixr 7 +:
-- 
-- {- | Internal function. Adds a term to a finite list. Grading ignorant.
-- 
-- Examples:
-- 
-- >>> (term 1 [1]) +: (fromListS [term 1 [1], term 1 [2]])
-- (2 *^ [1] + 1 *^ [2])
-- >>> (term 1 [3]) +: (fromListS [(1, 1), (1, 2)])
-- (1 *^ [3] + 1 *^ [1] + 1 *^ [2])
-- 
-- Properties:
-- 
-- prop> (length $ t +: l) - 1 <= length (l :: Sum Integer Integer)
-- -}
-- (+:) :: (Num k, Eq k, Eq a) => Term k a -> Sum k a -> Sum k a
-- (+:) (0 :*^ _) s = s
-- (+:) t s = case maybeAddTerm t s of
--     Nothing -> Sum t s
--     Just s' -> s'
--   where
--     maybeAddTerm t1 Zero = Nothing
--     maybeAddTerm t1 (t2 :+ s2) =
--         if t1_basis == (getBasis t2)
--             then
--                 if scalar_sum /= 0
--                     then Just $ Sum (scalar_sum *^ t1_basis) s2
--                     else Just s2
--             else case maybeAddTerm t1 s2 of
--                 Nothing -> Nothing
--                 Just s2' -> Just $ Sum t2 s2'
--       where
--         t1_basis = getBasis t1
--         scalar_sum = (getScalar t1) + (getScalar t2)
-- 
-- instance (Num k, Eq k, Eq a) => Semigroup (Sum k a) where
--     Zero <> s2 = s2
--     s1 <> Zero = s1
--     (t :+ s1) <> s2 = t +: (s1 <> s2)
-- 
-- instance (Num k, Eq k, Eq a) => Monoid (Sum k a) where
--     mempty = Zero
-- 
-- instance (Num k, Eq k, Eq a) => Group (Sum k a) where
--     invert Zero = Zero
--     invert (t :+ s) = ((negate $ getScalar t) *^ (getBasis t)) +: (invert s)
-- 
-- instance (Num k, Eq k, Eq a) => Eq (Sum k a) where
--     s1 == s2 = (s1 <> (invert s2)) == Zero
-- 
-- instance (Num k, Eq k, Eq a) => Num (Sum k a) where
--     (+) = (<>)
-- 
--     negate = invert
-- 
--     a * b = fromListS $ map mconcat $ distributeLists ab_list
--       where
--         ab_list = [toListS a, toListS b]
-- 
--     fromInteger n = ((fromInteger n) *^ One) +: Zero
-- 
--     abs = error "abs not implemented for Algebra"
-- 
--     signum = error "signum not implemented for Algebra"
-- 
-- 
-- --------------- PowerSeries ----------------
-- 
-- infixr 6 :&
-- 
-- data PowerSeries k a = (Sum k a) :& (PowerSeries k a) | Empty deriving (Eq)
-- 
-- fromListPS :: [Sum k a] -> PowerSeries k a
-- fromListPS [] = Empty
-- fromListPS (h : t) = h :& fromListPS t
-- 
-- toListPS :: PowerSeries k a -> [Sum k a]
-- toListPS Empty = []
-- toListPS (h :& ps) = h : toListPS ps
-- 
-- instance (Show k, Show a) => Show (PowerSeries k a) where
--     show ps = show_ 0 ps
--       where
--         show_ n Empty = "_" ++ show n
--         show_ n (h :& Empty) = "(" ++ show h ++ ")_" ++ show n
--         show_ n (h :& ps) = "(" ++ show h ++ ")_" ++ show n ++ " + " ++ show_ (n + 1) ps
-- 
-- instance (Num k, Eq a) => Semigroup (PowerSeries k a) where
--     Empty <> ps = ps
--     ps <> Empty = ps
--     (h1 :& ps1) <> (h2 :& ps2) = (h1 <> h2) :& (ps1 <> ps2)
-- 
-- instance (Num k, Eq a) => Monoid (PowerSeries k a) where
--     mempty = Empty
-- 
-- instance (Num k, Eq a) => Group (PowerSeries k a) where
--     invert Empty = Empty
--     invert (h :& ps) = (invert h) :& (invert ps)
-- 
-- instance (Num k, Eq a) => Num (PowerSeries k a) where
--     (+) = (<>)
-- 
--     negate = invert
-- 
--     a * b = fromListPS $ map sum $ map (map product) $ distributeGradedLists ab_list
--       where
--         ab_list = [toListPS a, toListPS b]
-- 
--     fromInteger n = (fromInteger n) :& Empty
-- 
--     abs = error "abs not implemented for GradedAlgebra"
-- 
--     signum = error "signum not implemented for GradedAlgebra"
-- 
-- 
--------------- Product ----------------
--
-- data Product b = b :* (Product b) | One deriving (Eq)
-- 
-- infixr 7 :*
-- 
-- instance Graded b => Graded (Product b) where
--     grading One = 0
--     grading (t :* p) = grading t + grading p
-- 
-- instance (Show b) => Show (Product b) where
--     show One = "1"
--     show (t :* One) = show t
--     show (t :* p) = show t ++ " * " ++ show p
-- 
-- instance Semigroup (Product b) where
--     One <> p = p
--     p <> One = p
--     (t :* p1) <> p2 = t :* (p1 <> p2)
-- 
-- instance Monoid (Product b) where
--     mempty = One
-- 
--
--
--------------- Algebra2 ----------------
--
-- type Algebra2 sc b = Sum sc (Product b, Product b)
-- 
-- instance (Scalar sc, Eq b) => Num (Algebra2 sc b) where
--     (+) = (<>)
-- 
--     negate = invert
-- 
--     a * b = fromListS $ map mconcat $ distributeLists ab_list
--       where
--         ab_list = [toListS a, toListS b]
-- 
--     fromInteger n = (term (fromInteger n) (One, One)) +: Zero
-- 
--     abs = error "abs not implemented for Algebra2"
-- 
--     signum = error "signum not implemented for Algebra2"
-- 
-- type GradedAlgebra2 sc b = PowerSeries (Algebra2 sc b)
-- 
-- 
-- instance (Scalar sc, Eq b) => Num (GradedAlgebra2 sc b) where
--     (+) = (<>)
-- 
--     negate = invert
-- 
--     a * b = fromListPS $ map sum $ map (map product) $ distributeGradedLists ab_list
--       where
--         ab_list = [toListPS a, toListPS b]
-- 
--     fromInteger n = (fromInteger n) :& Empty
-- 
--     abs = error "abs not implemented for GradedAlgebra2"
-- 
--     signum = error "signum not implemented for GradedAlgebra2"
